# Spring Boot configuration

# Logger configuration
logging: 
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: ERROR
  # Server configuration
server:
  port: 9080
  sessionTimeout: 30
 